routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();


Route::resource('customers','CustomerController');
Route::resource('categories','CategoryController');
Route::resource('items','ItemController');
Route::resource('details','DetailController');
Route::resource('transactions','TransactionController');
Route::resource('users','UserController');
Route::get('/session/tampil','SesiController@tampilkanSession');
Route::post('/session/buat','SesiController@buatSession');
Route::get('/session/hapus','SesiController@hapusSession');
Route::get('pilih/barang', 'SesiController@index');
Route::get('cart', 'SesiController@cart');
Route::get('add-to-cart/{id}', 'SesiController@addToCart');
Route::patch('update-cart', 'SesiController@update');
 
Route::delete('remove-from-cart', 'SesiController@remove');

Route::get('/home', 'HomeController@index')->name('home');

app/Http/Controllers/TransactionController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Input;
use Illuminate\Support\Facades\DB;
use App\Sale;
use App\Customer;
use App\Detail;
use App\Product;
use Auth;

class TransactionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $transactions = Sale::all();
        $customer = Customer::all(); 
        $detail = Detail::all();
        $c_detail = count($detail);
        return view('transactions.show', [
            'transactions' => $transactions,
            'customer' => $customer,
            'c_detail' => $c_detail,
            'details' => $detail
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if (Auth::user()->level == 1) {
            $product = Product::all();
            $customer = Customer::all();
            $transaction = Sale::all();
            return view('transactions.add', [
                'product' => $product,
                'customer' => $customer,
                'transactions' => $transaction
            ]);
        } else {
            return redirect()->route('home');
        }
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        DB::beginTransaction();
        try{
                    // Step 1 : Create User
                    $transaction = new Sale();
                    $transaction->customer_id = $request->customer;
                    $transaction->total = $request->total;
                    $transaction->save();
        }catch(\Exception $e){
                    DB::rollback();
                    return redirect()->route('home')
                                ->with('warning','Something Went Wrong!');
        }
         
        try{
                    //Step 2 : Stripe Api Call 
         
                    //Step 3 : Amount Charged
                foreach (session('cart') as $id => $details) {
                    $detail = new Detail();
                    $detail->qty = $details['qty'];
                    $detail->price = $details['price'];
                    $detail->subtotal = $details['qty']*$details['price'];
                    $detail->product_id = $id;
                    $detail->sale_id = $transaction->id;
                    $detail->save();
                }
        }catch(\Exception $e){
                    DB::rollback();
                    return redirect()->route('transactions.index')
                                ->with('warning','Something Went Wrong!');
        }
        DB::commit(); // All transaction will commit if statement reach on this
        foreach (session('cart') as $id => $details) {
            $product = Product::where('id', $id)->get();
            foreach ($product as $products) {
                $old_stock = $products['stock'];
            }
            $s_stock = $details['qty'];
            $k_stock = DB::table('products')->where('id', $id)->update(['stock' => $old_stock-$s_stock]);

            $request->session()->forget('cart');
        }
        return redirect()->route('transactions.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $transaction = Sale::where('id', $id)->get();
        $detail = Detail::where('sale_id', $id)->get();
        $totals = $detail->sum('subtotal');
        $c_detail = $detail->count('id');
        return view('transactions.detail', [
            'transaction' => $transaction,
            'detail' => $detail,
            'c_detail' => $c_detail,
            'totals' => $totals
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $detail = Detail::find($id);
        $product = Product::all();
        $customer = Customer::all();
        $transaction = Sale::all();
        return view('transactions.edit', [
            'detail' => $detail,
            'transactions' => $transaction,
            'customer' => $customer,
            'product' => $product
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $detail = Detail::find($id);
        $detail->qty = $request->qty;
        $detail->price = $request->price;
        $detail->subtotal = ($request->qty * $request->price);
        $detail->product_id = $request->product;
        $detail->sale_id = $request->transaction;

        $detail->update();
        return redirect()->route('transactions.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Sale::where('id',$id)->delete();
        Detail::where('id',$id)->delete();
        return redirect()->back();
    }

}

resources/views/transactions/add.blade.php
@extends('layouts.app')

@section('content')
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Transaction
        <small>Transaction Product</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href=""><i class="fa fa-shopping-cart"></i>Transaction</a></li>
      </ol>
    </section>


    <!-- Main content -->
    <section class="content">
      <div class="box">
        <div class="box-header">
            <h3 class="box-title">Transaction</h3>
            <div class="pull-right">
                <a href="." class="btn btn-warning btn-flat"> <i class="fa fa-undo"></i> Back</a>
            </div>
        </div>
        <div class="box-body">
            <div class="row">
                <div class="col-md-12 col-md-offset-0">
                    <form action="{{route('transactions.store')}}" method="post">
                        {{ csrf_field() }}
                        <div class="form-group">
                            <label for="customer">Customer :</label>
                            <input type="hidden" name="id" value="">
                            <select name="customer" id="customer" class="form-control">
                                <option value="">--Pilih--</option>
                                @foreach($customer as $customers)
                                <option value="{{$customers->id}}">{{$customers->name}}</option>
                                @endforeach
                            </select>
                        </div>

                        <label>Daftar Barang :</label>
                        <div class="box-body table-responsive">
                        <table class="table  table-striped" id="cart">
                            <thead>
                            <tr>
                                <th class="text-center">Product</th>
                                <th class="text-center">Price</th>
                                <th style="width: 10%;" class="text-center">qty</th>
                                <th class="text-center">Subtotal</th>
                            </tr>
                            </thead>
                            <tbody>

                            <?php $total = 0 ?>

                            @if(session('cart'))
                                @foreach(session('cart') as $id => $details)

                                    <?php $total += $details['price'] * $details['qty'] ?>

                                    <tr>
                                        <td class="text-center" data-th="Product">
                                            <div class="row">
                                                <div class="col-sm-9">
                                                    <h4 class="nomargin">{{ $details['name'] }}</h4>
                                                </div>
                                            </div>
                                        </td>
                                        <td class="text-center" data-th="Price">Rp. {{ $details['price'] }}</td>
                                        <td class="text-center" data-th="qty">
                                            <div class="row">
                                                <div class="col-sm-9">
                                                    <h4 class="nomargin">{{ $details['qty'] }}</h4>
                                                </div>
                                            </div>
                                        </td>
                                        <td class="text-center" data-th="Subtotal" class="text-center">Rp. {{ $details['price'] * $details['qty'] }}</td>
                                    </tr>
                                @endforeach
                            @endif

                            </tbody>
                            <tfoot>
                            <tr class="visible-xs">
                                <td class="text-center"><strong>Total {{ $total }}</strong></td>
                            </tr>
                            <tr>
                                <td>
                                </td>
                                <td colspan="2" class="hidden-xs"></td>
                                <td class="hidden-xs text-center"><strong>Total Rp. {{ $total }}</strong></td>
                            </tr>
                            </tfoot>
                        </table>
                        </div>

                        <label>Uang pembeli :</label>
                        <div class="input-group margin">
                            <input type="hidden" name="total" value="{{$total}}">
                            <input type="number" name="uang" class="form-control">
                        </div>

                        <div class="form-group">
                            <button type="reset" class="btn pull-right"style="margin-right: 5px;">Reset</button>
                            <button type="submit" name="" class="btn btn-warning pull-right"style="margin-right: 5px;"> <i class="fa fa-paper-plane"></i> Save</button>
                        </div>
                    </form>
            </div>
        </div>
      </div>
    </section>
@endsection

resources/views/transactions/cart.blade.php
@extends('layouts.app')

@section('content')

    @if(session('success'))

        <div class="alert alert-success margin">
            {{ session('success') }}
        </div>

    @endif
<section class="content">
    <div class="box">
    <h2 class="margin">Daftar barang yang dibeli :</h2>
    <div class="box-body table-responsive">
    <table class="table  table-striped" id="cart">
        <thead>
        <tr>
            <th class="text-center">Product</th>
            <th class="text-center">Price</th>
            <th style="width: 10%;" class="text-center">qty</th>
            <th class="text-center">Subtotal</th>
            <th class="text-center">Action</th>
        </tr>
        </thead>
        <tbody>

        <?php $total = 0 ?>

        @if(session('cart'))
            @foreach(session('cart') as $id => $details)

                <?php $total += $details['price'] * $details['qty'] ?>

                <tr>
                    <td data-th="Product">
                        <div class="row">
                            <div class="col-sm-9">
                                <h4 class="nomargin">{{ $details['name'] }}</h4>
                            </div>
                        </div>
                    </td>
                    <td data-th="Price">Rp. {{ $details['price'] }}</td>
                    <td data-th="qty">
                        <input type="number" value="{{ $details['qty'] }}" class="qty form-control" />
                    </td>
                    <td data-th="Subtotal" class="text-center">Rp. {{ $details['price'] * $details['qty'] }}</td>
                    <td class="actions" data-th="">
                        <button class="btn btn-info btn-sm update-cart" data-id="{{ $id }}"><i class="fa fa-refresh"></i></button>
                        <button class="btn btn-danger btn-sm remove-from-cart" data-id="{{ $id }}"><i class="fa fa-trash-o"></i></button>
                    </td>
                </tr>
            @endforeach
        @endif

        </tbody>
        <tfoot>
        <tr class="visible-xs">
            <td class="text-center"><strong>Total {{ $total }}</strong></td>
        </tr>
        <tr>
            <td><a href="{{ url('/transactions/create') }}" class="btn btn-warning"><i class="fa fa-angle-left"></i>&nbsp;Lanjutkan</a>
            <a href="/pilih/barang" class="btn btn-default"><i class="fa fa-undo"></i>&nbsp;Back</a>
            </td>
            <td colspan="2" class="hidden-xs"></td>
            <td class="hidden-xs text-center"><strong>Total Rp. {{ $total }}</strong></td>
        </tr>
        </tfoot>
    </table>
    </div>
    </div>
</section>
@endsection

resources/views/transactions/detail.blade.php
@extends('layouts.app')

@section('content')

@if($c_detail != 0)
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Transaction
        <small>Detail</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href=""><i class="fa fa-shopping-cart"></i>Transaction</a></li>
        <li class="active">Detail</li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="box">
        <div class="box-header">
            <h3 class="box-title">Detail Transaction</h3>
            <div class="pull-right">
                <a href="{{ route('transactions.index') }}" class="btn btn-default btn-flat"> <i class="fa fa-undo"></i> Back</a>
            </div>
        </div>
        <div class="box-body table-responsive">
            <table class="table table-bordered table-striped" id="table1">
                <thead>
                    <tr>
                        <th class="text-center">Transaction Id</th>
                        <th class="text-center">Detail Id</th>
                        <th class="text-center">Product Id</th>
                        <th class="text-center">Qty</th>
                        <th class="text-center">Price</th>
                        <th class="text-center">Subtotal</th>
                        <th class="text-center">Action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($detail as $details)
                    @if(Auth::user()->id)
                    <tr>
                        <td class="text-center">{{ $details->sale_id }}</td>
                        <td class="text-center">{{ $details->id }}</td>
                        <td class="text-center">{{ $details->product_id }}</td>
                        <td class="text-center">{{ $details->qty }}</td>
                        <td class="text-center">{{ $details->price }}</td>
                        <td class="text-center">{{ $details->subtotal }}</td>
                        <td class="text-center">
                        @foreach($transaction as $transactions)
                        @if($transactions->total == '')
                        <a href="{{ route('transactions.edit', $details->id)}}" class="btn btn-warning btn-xs"> <i class="fa fa-pencil"></i> Edit</a>
                        @else
                        @endif
                        @endforeach
                            <form method="POST" id="delete-form-{{ $details->id }}" action="{{ route('transactions.destroy', $details->id) }}" style="display: none">
                            {{ csrf_field() }} {{ method_field('DELETE') }}
                            </form>
                              <a  class="btn btn-danger btn-xs" type="button" onclick="
                              if(confirm('Are you sure, want to delete {{ $details->id }}')) {
                                event.preventDefault(); document.getElementById('delete-form-{{ $details->id }}').submit();
                              } else {
                                event.preventDefault();
                              }
                              ">Delete</a>
                        </td>
                    </tr>
                    @endif
                    @endforeach
                </tbody>
            </table>
            <div class="pull-right">
            <h2>Total: {{$totals}}</h2>
            </div>
        </div>
      </div>

    @if($transactions->total =='')  
    <div class="box">
        <div class="box-header">
            <h2>
            <p class="margin" style="margin-bottom: 20px;">Uang Pembeli</p>
            </h2>
            <form method="POST" action="{{ route('details.store') }}">
            {{ csrf_field() }}
            <div class="input-group margin">
                <input type="hidden" name="id" value="{{$details->sale_id}}">
                <input type="hidden" name="total" value="{{$totals}}">
                <input type="number" name="uang" class="form-control">
                    <span class="input-group-btn">
                      <button type="submit" class="btn btn-warning btn-flat">Bayar!</button>
                    </span>
            </div>
            </form>
        </div>
    </div>
    @else
    @endif
    </section>
@else

    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Transaction
        <small>Detail</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href=""><i class="fa fa-group"></i>Transaction</a></li>
        <li class="active">Detail</li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="box">
        <div class="box-header">
            <h3 class="box-title">Detail Transaction</h3>
            <div class="pull-right">
                <a href="{{ route('transactions.index') }}" class="btn btn-default btn-flat"> <i class="fa fa-undo"></i> Back</a>
            </div>
        </div>
        <div class="box-body table-responsive">
            <div class="alert alert-danger alert-dismissible margin">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <h4><i class="icon fa fa-ban"></i> Data Kosong!</h4>
            Empty!
            </div>
            <div class="pull-right">
            </div>
        </div>
      </div>
    

    </section>

@endif
@endsection

resources/views/transactions/edit.blade.php
@extends('layouts.app')

@section('content')
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Transaction
        <small>Transaction Product</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href=""><i class="fa fa-shopping-cart"></i>Transaction</a></li>
      </ol>
    </section>


    <!-- Main content -->
    <section class="content">
      <div class="box">
        <div class="box-header">
            <h3 class="box-title">Transaction</h3>
            <div class="pull-right">
                <a href="../" class="btn btn-warning btn-flat"> <i class="fa fa-undo"></i> Back</a>
            </div>
        </div>
        <div class="box-body">
            <div class="row">
                <div class="col-md-12 col-md-offset-0">
                    <form action="{{ route('transactions.update', $detail->id) }}" method="post">
                        {{ csrf_field() }}
                        {{ method_field('PATCH') }}
                        <div class="form-group">
                            <label for="customer">Customer :</label>
                            <input type="hidden" name="id" value="">
                            <select name="customer" id="customer" class="form-control">
                                <option value="">--Pilih--</option>
                                @foreach($customer as $customers)
                                <option value="{{$customers->id}}">{{$customers->name}}</option>
                                @endforeach
                            </select>
                        </div>

                        <label>Daftar Barang :</label>
                        <div class="box-body table-responsive">
                        
                        <table class="table  table-striped" id="cart">
                            <thead>
                            <tr>
                                <th class="text-center">Product</th>
                                <th class="text-center">Price</th>
                                <th style="width: 10%;" class="text-center">qty</th>
                                <th class="text-center">Subtotal</th>
                                <th class="text-center">Action</th>
                            </tr>
                            </thead>
                            <tbody>

                            <?php $total = 0 ?>

                            @if(session('cart'))
                                @foreach(session('cart') as $id => $details)

                                    <?php $total += $details['price'] * $details['qty'] ?>

                                    <tr>
                                        <td class="text-center" data-th="Product">
                                            <div class="row">
                                                <div class="col-sm-9">
                                                    <h4 class="nomargin">{{ $details['name'] }}</h4>
                                                </div>
                                            </div>
                                        </td>
                                        <td  class="text-center" data-th="Price">Rp. {{ $details['price'] }}</td>
                                        <td  class="text-center" data-th="qty">
                                            <input type="number" value="{{ $details['qty'] }}" class="qty form-control" />
                                        </td>
                                        <td  class="text-center" data-th="Subtotal" class="text-center">Rp. {{ $details['price'] * $details['qty'] }}</td>
                                        <td  class="text-center" class="actions" data-th="">
                                            <button class="btn btn-info btn-sm update-cart" data-id="{{ $id }}"><i class="fa fa-refresh"></i></button>
                                            <button class="btn btn-danger btn-sm remove-from-cart" data-id="{{ $id }}"><i class="fa fa-trash-o"></i></button>
                                        </td>
                                    </tr>
                                @endforeach
                            @endif

                            </tbody>
                            <tfoot>
                            <tr class="visible-xs">
                                <td class="text-center"><strong>Total {{ $total }}</strong></td>
                            </tr>
                            <tr>
                                <td></td>
                                <td colspan="2" class="hidden-xs"></td>
                                <td class="hidden-xs text-center"><strong>Total Rp. {{ $total }}</strong></td>
                            </tr>
                            </tfoot>
                        </table>
                        </div>
                        <div class="form-group">
                            <button type="reset" class="btn pull-right" style="margin-right: 5px;">Reset</button>
                            <button type="submit" name="" class="btn btn-warning pull-right" style="margin-right: 5px;"> <i class="fa fa-paper-plane"></i> Save</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
      </div>
    </section>
@endsection

resources/views/transactions/product.blade.php
@extends('layouts.app')
 
@section('content')
 
    <div class="container products">
        
        <div class="row margin" style="background-color: white;">
            <h2 class="margin">Pilih Barang yang mau dibeli :
            </h2>
            <div class="col-sm-12" style="margin-bottom: 15px;">
                <form action="/pilih/barang/" method="get">
                <div class="input-group input-group-sm">
                <input type="text" class="form-control" name="search">
                    <span class="input-group-btn">
                      <button type="button" class="btn btn-info btn-flat">Cari</button>
                    </span>

                </div>
                </form>
            </div>
        </div>
        <div class="row">
 
            @foreach($products as $product)
                <div class="col-xs-18 col-sm-6 col-md-3 margin">
                    <div class="thumbnail">
                        <div class="caption">
                            <h4>{{ $product->id }}</h4>
                            <p>{{ $product->name }}</p>
                            <p><strong>Stock: </strong>{{ $product->stock == '' ? 'Habis' : $product->stock }}</p>
                            <p><strong>Price: </strong>Rp. {{ $product->price }}</p>
                            <p class="btn-holder">
                            @if($product->stock == '')
                                <button href="{{ url('add-to-cart/'.$product->id) }}" class="btn btn-warning btn-block text-center" role="button" disabled>Add to cart</button>
                            @else
                                <a href="{{ url('add-to-cart/'.$product->id) }}" class="btn btn-warning btn-block text-center" role="button">Add to cart</a>
                            @endif
                            </p>
                        </div>
                    </div>
                </div>
            @endforeach
 
        </div><!-- End row -->

        @if($search != '')
        <div class="row margin">
                <a href="/pilih/barang"><button class="btn btn-default">Back</button></a>
        </div>
        @endif
 
        <div class="row margin" style="background-color: white;">
            <h2 class="margin">Lihat Barang yang dibeli : (<a href="/cart">Show</a>)</h2>
        </div>

    </div>
 
@endsection

resources/views/transactions/show.blade.php
@extends('layouts.app')

@section('content')
@csrf
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Transaction
        <small>Transaction Data</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href=""><i class="fa fa-shopping-cart"></i>Transaction</a></li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="box">
        <div class="box-header">
            <h3 class="box-title">Transaction Data</h3>
            <div class="pull-right">
                <a href="/pilih/barang" class="btn btn-warning btn-flat"> <i class="fa fa-plus"></i> Create</a>
            </div>
        </div>
        <div class="box-body table-responsive">
            <table class="table table-bordered table-striped" id="table1">
                <thead>
                    <tr>
                        <th class="text-center">Id</th>
                        <th class="text-center">Customer Id</th>
                        <th class="text-center">Status</th>
                        <th class="text-center">Action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($transactions as $transaction)
                    @if(Auth::user()->id)
                    <tr>
                        <td class="text-center">{{$transaction->id}}</td>
                        <td class="text-center">{{$transaction->customer_id}}</td>
                        <td class="text-center">
                            @if($transaction->total != '')
                                <li class="fa fa-check"></li>
                            @else
                                <li class="fa fa-close"></li>
                            @endif
                        </td>
                        <td class="text-center">
                            <form method="POST" id="delete-form-{{ $transaction->id }}" action="{{ route('transactions.destroy', $transaction->id) }}" style="display: none">
                            {{ csrf_field() }} {{ method_field('DELETE') }}
                            </form>
                              <a  class="btn btn-danger btn-xs" type="button" onclick="
                              if(confirm('Are you sure, want to delete {{ $transaction->id }}')) {
                                event.preventDefault(); document.getElementById('delete-form-{{ $transaction->id }}').submit();
                              } else {
                                event.preventDefault();
                              }
                              ">Delete</a>
                        </td>
                    </tr>
                    @endif
                    @endforeach
                </tbody>
            </table>
        </div>
      </div>
    </section>
@endsection

resources/views/transactions/success.blade.php
@extends('layouts.app')

@section('content')

@if($kembalian > 0)
<div class="alert alert-success alert-dismissible margin">
<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
<h4><i class="icon fa fa-check"></i> Success!</h4>
Kembaliannya {{$kembalian}}
</div>
</div>
@endif

@if($kembalian < 0)
  <div class="alert alert-danger alert-dismissible margin">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    <h4><i class="icon fa fa-ban"></i> Kurang!</h4>
    Uang {{$kembalian}}
  </div>
@endif

@endsection